import { readFile, writeFile, mkdir, rm, copyFile, cp } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const dist = new URL('../dist/', import.meta.url);
const EXPECTED_SHA = '2afea9ccffb7dff34fa581528eb669d0b2df996872a3e8d59f369d145fd0be55';
await rm(dist,{recursive:true,force:true});
await mkdir(new URL('../dist/assets/',import.meta.url),{recursive:true});
await copyFile(new URL('../index.html',import.meta.url),new URL('../dist/index.html',import.meta.url));
await copyFile(new URL('../src/app.js',import.meta.url),new URL('../dist/assets/app.js',import.meta.url));
await copyFile(new URL('../src/index.css',import.meta.url),new URL('../dist/assets/index.css',import.meta.url));
await copyFile(new URL('../src/contract-config.js',import.meta.url),new URL('../dist/assets/contract-config.js',import.meta.url));
await cp(new URL('../public/',import.meta.url),dist,{recursive:true});
const source=await readFile(new URL('../contracts/ConsentGuard.py',import.meta.url));
const sha=createHash('sha256').update(source).digest('hex');
if(sha!==EXPECTED_SHA) throw new Error(`Contract source changed: ${sha}`);
const cfg=await readFile(new URL('../src/contract-config.js',import.meta.url),'utf8');
const match=cfg.match(/contractAddress:\s*'([^']*)'/);
const address=match?.[1]||'';
if(!/^0x[a-fA-F0-9]{40}$/.test(address)) throw new Error(`Invalid configured contract address: ${address}`);
const manifest={name:'ConsentGuard',network:'GenLayer StudioNet',contract:address,contract_source_sha256:sha,built_at:new Date().toISOString()};
await writeFile(new URL('../dist/build-manifest.json',import.meta.url),JSON.stringify(manifest,null,2)+'\n');
console.log('PASS production build');
console.log(`PASS contract ${address}`);
console.log(`PASS source SHA ${sha}`);
